# Generated by Django 3.1.1 on 2020-10-22 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201019_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
